
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package lexer;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\002\004\000\002\002\003\000\002\002" +
    "\005\000\002\003\005\000\002\004\003\000\002\004\004" +
    "\000\002\004\004\000\002\005\006\000\002\005\006\000" +
    "\002\005\004\000\002\005\005\000\002\005\005\000\002" +
    "\005\011\000\002\005\011\000\002\005\004\000\002\005" +
    "\004\000\002\005\004\000\002\010\005\000\002\010\005" +
    "\000\002\010\004\000\002\010\005\000\002\010\005\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\010\005\000\002\010\003\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\011\004" +
    "\000\002\011\005\000\002\011\003\000\002\011\003\000" +
    "\002\011\003\000\002\006\003\000\002\006\004\000\002" +
    "\006\004\000\002\007\005\000\002\007\007\000\002\007" +
    "\007\000\002\007\007\000\002\007\007\000\002\007\007" +
    "\000\002\007\007\000\002\007\007\000\002\007\007\000" +
    "\002\007\007\000\002\007\007\000\002\007\007\000\002" +
    "\007\007\000\002\007\007\000\002\007\007\000\002\007" +
    "\007\000\002\012\007\000\002\012\003\000\002\013\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\004\004\006\001\002\000\004\002\245\001" +
    "\002\000\006\002\000\037\113\001\002\000\016\006\007" +
    "\007\012\012\016\015\015\016\011\062\014\001\002\000" +
    "\004\062\107\001\002\000\026\003\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\011\ufffd\012\ufffd\014\ufffd\015\ufffd\016\ufffd\062" +
    "\ufffd\001\002\000\004\062\106\001\002\000\004\035\100" +
    "\001\002\000\022\003\052\005\077\006\007\007\012\012" +
    "\016\015\015\016\011\062\014\001\002\000\004\023\074" +
    "\001\002\000\020\020\024\034\020\035\023\062\022\063" +
    "\026\064\025\065\072\001\002\000\004\035\017\001\002" +
    "\000\016\020\024\034\020\035\023\062\022\063\026\064" +
    "\025\001\002\000\016\020\024\034\020\035\023\062\022" +
    "\063\026\064\025\001\002\000\060\003\uffe7\005\uffe7\006" +
    "\uffe7\007\uffe7\011\uffe7\012\uffe7\014\uffe7\015\uffe7\016\uffe7" +
    "\017\057\020\060\021\062\022\061\024\uffe7\025\uffe7\026" +
    "\uffe7\027\uffe7\030\uffe7\031\uffe7\032\uffe7\033\uffe7\036\uffe7" +
    "\062\uffe7\001\002\000\064\003\uffde\005\uffde\006\uffde\007" +
    "\uffde\011\uffde\012\uffde\014\uffde\015\uffde\016\uffde\017\uffde" +
    "\020\uffde\021\uffde\022\uffde\024\uffde\025\uffde\026\uffde\027" +
    "\uffde\030\uffde\031\uffde\032\uffde\033\uffde\036\uffde\060\uffde" +
    "\061\uffde\062\uffde\001\002\000\014\020\024\035\023\062" +
    "\022\063\026\064\025\001\002\000\014\020\024\035\023" +
    "\062\022\063\026\064\025\001\002\000\064\003\uffdf\005" +
    "\uffdf\006\uffdf\007\uffdf\011\uffdf\012\uffdf\014\uffdf\015\uffdf" +
    "\016\uffdf\017\uffdf\020\uffdf\021\uffdf\022\uffdf\024\uffdf\025" +
    "\uffdf\026\uffdf\027\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf" +
    "\036\uffdf\060\uffdf\061\uffdf\062\uffdf\001\002\000\064\003" +
    "\uffe0\005\uffe0\006\uffe0\007\uffe0\011\uffe0\012\uffe0\014\uffe0" +
    "\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021\uffe0\022\uffe0\024" +
    "\uffe0\025\uffe0\026\uffe0\027\uffe0\030\uffe0\031\uffe0\032\uffe0" +
    "\033\uffe0\036\uffe0\060\uffe0\061\uffe0\062\uffe0\001\002\000" +
    "\024\024\035\025\036\026\034\027\031\030\032\031\040" +
    "\032\030\033\037\036\033\001\002\000\016\020\024\034" +
    "\020\035\023\062\022\063\026\064\025\001\002\000\016" +
    "\020\024\034\020\035\023\062\022\063\026\064\025\001" +
    "\002\000\016\020\024\034\020\035\023\062\022\063\026" +
    "\064\025\001\002\000\004\013\046\001\002\000\016\020" +
    "\024\034\020\035\023\062\022\063\026\064\025\001\002" +
    "\000\016\020\024\034\020\035\023\062\022\063\026\064" +
    "\025\001\002\000\016\020\024\034\020\035\023\062\022" +
    "\063\026\064\025\001\002\000\016\020\024\034\020\035" +
    "\023\062\022\063\026\064\025\001\002\000\016\020\024" +
    "\034\020\035\023\062\022\063\026\064\025\001\002\000" +
    "\050\003\uffe8\005\uffe8\006\uffe8\007\uffe8\011\uffe8\012\uffe8" +
    "\014\uffe8\015\uffe8\016\uffe8\024\uffe8\025\uffe8\026\uffe8\027" +
    "\uffe8\030\uffe8\031\uffe8\032\uffe8\033\uffe8\036\uffe8\062\uffe8" +
    "\001\002\000\050\003\ufff0\005\ufff0\006\ufff0\007\ufff0\011" +
    "\ufff0\012\ufff0\014\ufff0\015\ufff0\016\ufff0\024\035\025\036" +
    "\026\034\027\031\030\032\031\040\032\030\033\ufff0\036" +
    "\ufff0\062\ufff0\001\002\000\050\003\uffec\005\uffec\006\uffec" +
    "\007\uffec\011\uffec\012\uffec\014\uffec\015\uffec\016\uffec\024" +
    "\uffec\025\uffec\026\034\027\031\030\032\031\040\032\uffec" +
    "\033\uffec\036\uffec\062\uffec\001\002\000\050\003\uffed\005" +
    "\uffed\006\uffed\007\uffed\011\uffed\012\uffed\014\uffed\015\uffed" +
    "\016\uffed\024\uffed\025\uffed\026\034\027\031\030\032\031" +
    "\040\032\uffed\033\uffed\036\uffed\062\uffed\001\002\000\050" +
    "\003\uffeb\005\uffeb\006\uffeb\007\uffeb\011\uffeb\012\uffeb\014" +
    "\uffeb\015\uffeb\016\uffeb\024\uffeb\025\uffeb\026\uffeb\027\uffeb" +
    "\030\uffeb\031\uffeb\032\uffeb\033\uffeb\036\uffeb\062\uffeb\001" +
    "\002\000\016\006\007\007\012\012\016\015\015\016\011" +
    "\062\014\001\002\000\022\003\052\006\007\007\012\012" +
    "\016\014\050\015\015\016\011\062\014\001\002\000\026" +
    "\003\ufff4\005\ufff4\006\ufff4\007\ufff4\011\ufff4\012\ufff4\014" +
    "\ufff4\015\ufff4\016\ufff4\062\ufff4\001\002\000\026\003\ufffc" +
    "\005\ufffc\006\ufffc\007\ufffc\011\ufffc\012\ufffc\014\ufffc\015" +
    "\ufffc\016\ufffc\062\ufffc\001\002\000\026\003\ufffb\005\ufffb" +
    "\006\ufffb\007\ufffb\011\ufffb\012\ufffb\014\ufffb\015\ufffb\016" +
    "\ufffb\062\ufffb\001\002\000\050\003\uffe9\005\uffe9\006\uffe9" +
    "\007\uffe9\011\uffe9\012\uffe9\014\uffe9\015\uffe9\016\uffe9\024" +
    "\uffe9\025\uffe9\026\uffe9\027\uffe9\030\uffe9\031\uffe9\032\uffe9" +
    "\033\uffe9\036\uffe9\062\uffe9\001\002\000\050\003\uffea\005" +
    "\uffea\006\uffea\007\uffea\011\uffea\012\uffea\014\uffea\015\uffea" +
    "\016\uffea\024\uffea\025\uffea\026\uffea\027\uffea\030\uffea\031" +
    "\uffea\032\uffea\033\uffea\036\uffea\062\uffea\001\002\000\050" +
    "\003\uffef\005\uffef\006\uffef\007\uffef\011\uffef\012\uffef\014" +
    "\uffef\015\uffef\016\uffef\024\035\025\036\026\034\027\031" +
    "\030\032\031\040\032\uffef\033\uffef\036\uffef\062\uffef\001" +
    "\002\000\064\003\uffe2\005\uffe2\006\uffe2\007\uffe2\011\uffe2" +
    "\012\uffe2\014\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021" +
    "\uffe2\022\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2" +
    "\031\uffe2\032\uffe2\033\uffe2\036\uffe2\060\uffe2\061\uffe2\062" +
    "\uffe2\001\002\000\014\020\024\035\023\062\022\063\026" +
    "\064\025\001\002\000\014\020\024\035\023\062\022\063" +
    "\026\064\025\001\002\000\014\020\024\035\023\062\022" +
    "\063\026\064\025\001\002\000\014\020\024\035\023\062" +
    "\022\063\026\064\025\001\002\000\064\003\uffe4\005\uffe4" +
    "\006\uffe4\007\uffe4\011\uffe4\012\uffe4\014\uffe4\015\uffe4\016" +
    "\uffe4\017\uffe4\020\uffe4\021\uffe4\022\uffe4\024\uffe4\025\uffe4" +
    "\026\uffe4\027\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4\036" +
    "\uffe4\060\uffe4\061\uffe4\062\uffe4\001\002\000\064\003\uffe3" +
    "\005\uffe3\006\uffe3\007\uffe3\011\uffe3\012\uffe3\014\uffe3\015" +
    "\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3\024\uffe3" +
    "\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3\032\uffe3\033" +
    "\uffe3\036\uffe3\060\uffe3\061\uffe3\062\uffe3\001\002\000\064" +
    "\003\uffe5\005\uffe5\006\uffe5\007\uffe5\011\uffe5\012\uffe5\014" +
    "\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021\062\022\061" +
    "\024\uffe5\025\uffe5\026\uffe5\027\uffe5\030\uffe5\031\uffe5\032" +
    "\uffe5\033\uffe5\036\uffe5\060\uffe5\061\uffe5\062\uffe5\001\002" +
    "\000\064\003\uffe6\005\uffe6\006\uffe6\007\uffe6\011\uffe6\012" +
    "\uffe6\014\uffe6\015\uffe6\016\uffe6\017\uffe6\020\uffe6\021\062" +
    "\022\061\024\uffe6\025\uffe6\026\uffe6\027\uffe6\030\uffe6\031" +
    "\uffe6\032\uffe6\033\uffe6\036\uffe6\060\uffe6\061\uffe6\062\uffe6" +
    "\001\002\000\014\017\057\020\060\021\062\022\061\036" +
    "\070\001\002\000\064\003\uffe1\005\uffe1\006\uffe1\007\uffe1" +
    "\011\uffe1\012\uffe1\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020" +
    "\uffe1\021\uffe1\022\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1" +
    "\030\uffe1\031\uffe1\032\uffe1\033\uffe1\036\uffe1\060\uffe1\061" +
    "\uffe1\062\uffe1\001\002\000\050\003\uffee\005\uffee\006\uffee" +
    "\007\uffee\011\uffee\012\uffee\014\uffee\015\uffee\016\uffee\024" +
    "\uffee\025\uffee\026\uffee\027\uffee\030\uffee\031\uffee\032\uffee" +
    "\033\uffee\036\uffee\062\uffee\001\002\000\026\003\ufff3\005" +
    "\ufff3\006\ufff3\007\ufff3\011\ufff3\012\ufff3\014\ufff3\015\ufff3" +
    "\016\ufff3\062\ufff3\001\002\000\046\003\ufff2\005\ufff2\006" +
    "\ufff2\007\ufff2\011\ufff2\012\ufff2\014\ufff2\015\ufff2\016\ufff2" +
    "\024\035\025\036\026\034\027\031\030\032\031\040\032" +
    "\030\033\037\062\ufff2\001\002\000\016\003\076\020\024" +
    "\035\023\062\022\063\026\064\025\001\002\000\036\003" +
    "\ufff7\005\ufff7\006\ufff7\007\ufff7\011\ufff7\012\ufff7\014\ufff7" +
    "\015\ufff7\016\ufff7\017\057\020\060\021\062\022\061\062" +
    "\ufff7\001\002\000\026\003\ufff6\005\ufff6\006\ufff6\007\ufff6" +
    "\011\ufff6\012\ufff6\014\ufff6\015\ufff6\016\ufff6\062\ufff6\001" +
    "\002\000\006\002\ufffe\037\ufffe\001\002\000\016\020\024" +
    "\034\020\035\023\062\022\063\026\064\025\001\002\000" +
    "\024\024\035\025\036\026\034\027\031\030\032\031\040" +
    "\032\030\033\037\036\102\001\002\000\004\010\103\001" +
    "\002\000\016\006\007\007\012\012\016\015\015\016\011" +
    "\062\014\001\002\000\022\003\052\006\007\007\012\011" +
    "\105\012\016\015\015\016\011\062\014\001\002\000\026" +
    "\003\ufff5\005\ufff5\006\ufff5\007\ufff5\011\ufff5\012\ufff5\014" +
    "\ufff5\015\ufff5\016\ufff5\062\ufff5\001\002\000\026\003\ufff1" +
    "\005\ufff1\006\ufff1\007\ufff1\011\ufff1\012\ufff1\014\ufff1\015" +
    "\ufff1\016\ufff1\062\ufff1\001\002\000\030\003\ufff8\005\ufff8" +
    "\006\ufff8\007\ufff8\011\ufff8\012\ufff8\014\ufff8\015\ufff8\016" +
    "\ufff8\023\110\062\ufff8\001\002\000\016\003\112\020\024" +
    "\035\023\062\022\063\026\064\025\001\002\000\036\003" +
    "\ufffa\005\ufffa\006\ufffa\007\ufffa\011\ufffa\012\ufffa\014\ufffa" +
    "\015\ufffa\016\ufffa\017\057\020\060\021\062\022\061\062" +
    "\ufffa\001\002\000\026\003\ufff9\005\ufff9\006\ufff9\007\ufff9" +
    "\011\ufff9\012\ufff9\014\ufff9\015\ufff9\016\ufff9\062\ufff9\001" +
    "\002\000\042\040\135\041\114\042\133\043\120\044\123" +
    "\045\122\046\126\047\134\050\127\051\115\052\130\053" +
    "\125\054\124\055\116\056\121\057\117\001\002\000\004" +
    "\023\241\001\002\000\004\023\235\001\002\000\004\023" +
    "\231\001\002\000\004\023\225\001\002\000\004\023\221" +
    "\001\002\000\004\023\215\001\002\000\004\023\211\001" +
    "\002\000\004\023\205\001\002\000\004\023\201\001\002" +
    "\000\004\023\175\001\002\000\004\023\171\001\002\000" +
    "\004\023\165\001\002\000\004\023\161\001\002\000\046" +
    "\002\uffff\003\157\040\135\041\114\042\133\043\120\044" +
    "\123\045\122\046\126\047\134\050\127\051\115\052\130" +
    "\053\125\054\124\055\116\056\121\057\117\001\002\000" +
    "\046\002\uffdd\003\uffdd\040\uffdd\041\uffdd\042\uffdd\043\uffdd" +
    "\044\uffdd\045\uffdd\046\uffdd\047\uffdd\050\uffdd\051\uffdd\052" +
    "\uffdd\053\uffdd\054\uffdd\055\uffdd\056\uffdd\057\uffdd\001\002" +
    "\000\004\023\153\001\002\000\004\023\140\001\002\000" +
    "\004\023\136\001\002\000\004\063\137\001\002\000\046" +
    "\002\uffda\003\uffda\040\uffda\041\uffda\042\uffda\043\uffda\044" +
    "\uffda\045\uffda\046\uffda\047\uffda\050\uffda\051\uffda\052\uffda" +
    "\053\uffda\054\uffda\055\uffda\056\uffda\057\uffda\001\002\000" +
    "\016\020\024\035\023\062\022\063\026\064\025\067\141" +
    "\001\002\000\004\060\uffc9\001\002\000\016\017\057\020" +
    "\060\021\062\022\061\060\uffc8\061\uffc8\001\002\000\004" +
    "\060\151\001\002\000\004\061\145\001\002\000\014\020" +
    "\024\035\023\062\022\063\026\064\025\001\002\000\004" +
    "\061\147\001\002\000\014\020\024\035\023\062\022\063" +
    "\026\064\025\001\002\000\004\060\uffca\001\002\000\004" +
    "\063\152\001\002\000\046\002\uffd3\003\uffd3\040\uffd3\041" +
    "\uffd3\042\uffd3\043\uffd3\044\uffd3\045\uffd3\046\uffd3\047\uffd3" +
    "\050\uffd3\051\uffd3\052\uffd3\053\uffd3\054\uffd3\055\uffd3\056" +
    "\uffd3\057\uffd3\001\002\000\016\020\024\035\023\062\022" +
    "\063\026\064\025\067\141\001\002\000\004\060\155\001" +
    "\002\000\004\063\156\001\002\000\046\002\uffd8\003\uffd8" +
    "\040\uffd8\041\uffd8\042\uffd8\043\uffd8\044\uffd8\045\uffd8\046" +
    "\uffd8\047\uffd8\050\uffd8\051\uffd8\052\uffd8\053\uffd8\054\uffd8" +
    "\055\uffd8\056\uffd8\057\uffd8\001\002\000\046\002\uffdb\003" +
    "\uffdb\040\uffdb\041\uffdb\042\uffdb\043\uffdb\044\uffdb\045\uffdb" +
    "\046\uffdb\047\uffdb\050\uffdb\051\uffdb\052\uffdb\053\uffdb\054" +
    "\uffdb\055\uffdb\056\uffdb\057\uffdb\001\002\000\046\002\uffdc" +
    "\003\uffdc\040\uffdc\041\uffdc\042\uffdc\043\uffdc\044\uffdc\045" +
    "\uffdc\046\uffdc\047\uffdc\050\uffdc\051\uffdc\052\uffdc\053\uffdc" +
    "\054\uffdc\055\uffdc\056\uffdc\057\uffdc\001\002\000\014\020" +
    "\024\035\023\062\022\063\026\064\025\001\002\000\014" +
    "\017\057\020\060\021\062\022\061\060\163\001\002\000" +
    "\004\063\164\001\002\000\046\002\uffd0\003\uffd0\040\uffd0" +
    "\041\uffd0\042\uffd0\043\uffd0\044\uffd0\045\uffd0\046\uffd0\047" +
    "\uffd0\050\uffd0\051\uffd0\052\uffd0\053\uffd0\054\uffd0\055\uffd0" +
    "\056\uffd0\057\uffd0\001\002\000\004\066\166\001\002\000" +
    "\004\060\167\001\002\000\004\063\170\001\002\000\046" +
    "\002\uffd2\003\uffd2\040\uffd2\041\uffd2\042\uffd2\043\uffd2\044" +
    "\uffd2\045\uffd2\046\uffd2\047\uffd2\050\uffd2\051\uffd2\052\uffd2" +
    "\053\uffd2\054\uffd2\055\uffd2\056\uffd2\057\uffd2\001\002\000" +
    "\016\020\024\035\023\062\022\063\026\064\025\067\141" +
    "\001\002\000\004\060\173\001\002\000\004\063\174\001" +
    "\002\000\046\002\uffd4\003\uffd4\040\uffd4\041\uffd4\042\uffd4" +
    "\043\uffd4\044\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4\051" +
    "\uffd4\052\uffd4\053\uffd4\054\uffd4\055\uffd4\056\uffd4\057\uffd4" +
    "\001\002\000\016\020\024\035\023\062\022\063\026\064" +
    "\025\067\141\001\002\000\004\060\177\001\002\000\004" +
    "\063\200\001\002\000\046\002\uffcf\003\uffcf\040\uffcf\041" +
    "\uffcf\042\uffcf\043\uffcf\044\uffcf\045\uffcf\046\uffcf\047\uffcf" +
    "\050\uffcf\051\uffcf\052\uffcf\053\uffcf\054\uffcf\055\uffcf\056" +
    "\uffcf\057\uffcf\001\002\000\016\020\024\035\023\062\022" +
    "\063\026\064\025\067\141\001\002\000\004\060\203\001" +
    "\002\000\004\063\204\001\002\000\046\002\uffce\003\uffce" +
    "\040\uffce\041\uffce\042\uffce\043\uffce\044\uffce\045\uffce\046" +
    "\uffce\047\uffce\050\uffce\051\uffce\052\uffce\053\uffce\054\uffce" +
    "\055\uffce\056\uffce\057\uffce\001\002\000\004\062\206\001" +
    "\002\000\004\060\207\001\002\000\004\063\210\001\002" +
    "\000\046\002\uffd6\003\uffd6\040\uffd6\041\uffd6\042\uffd6\043" +
    "\uffd6\044\uffd6\045\uffd6\046\uffd6\047\uffd6\050\uffd6\051\uffd6" +
    "\052\uffd6\053\uffd6\054\uffd6\055\uffd6\056\uffd6\057\uffd6\001" +
    "\002\000\014\020\024\035\023\062\022\063\026\064\025" +
    "\001\002\000\014\017\057\020\060\021\062\022\061\060" +
    "\213\001\002\000\004\063\214\001\002\000\046\002\uffd5" +
    "\003\uffd5\040\uffd5\041\uffd5\042\uffd5\043\uffd5\044\uffd5\045" +
    "\uffd5\046\uffd5\047\uffd5\050\uffd5\051\uffd5\052\uffd5\053\uffd5" +
    "\054\uffd5\055\uffd5\056\uffd5\057\uffd5\001\002\000\004\062" +
    "\216\001\002\000\004\060\217\001\002\000\004\063\220" +
    "\001\002\000\046\002\uffcc\003\uffcc\040\uffcc\041\uffcc\042" +
    "\uffcc\043\uffcc\044\uffcc\045\uffcc\046\uffcc\047\uffcc\050\uffcc" +
    "\051\uffcc\052\uffcc\053\uffcc\054\uffcc\055\uffcc\056\uffcc\057" +
    "\uffcc\001\002\000\004\066\222\001\002\000\004\060\223" +
    "\001\002\000\004\063\224\001\002\000\046\002\uffd7\003" +
    "\uffd7\040\uffd7\041\uffd7\042\uffd7\043\uffd7\044\uffd7\045\uffd7" +
    "\046\uffd7\047\uffd7\050\uffd7\051\uffd7\052\uffd7\053\uffd7\054" +
    "\uffd7\055\uffd7\056\uffd7\057\uffd7\001\002\000\014\020\024" +
    "\035\023\062\022\063\026\064\025\001\002\000\014\017" +
    "\057\020\060\021\062\022\061\060\227\001\002\000\004" +
    "\063\230\001\002\000\046\002\uffcb\003\uffcb\040\uffcb\041" +
    "\uffcb\042\uffcb\043\uffcb\044\uffcb\045\uffcb\046\uffcb\047\uffcb" +
    "\050\uffcb\051\uffcb\052\uffcb\053\uffcb\054\uffcb\055\uffcb\056" +
    "\uffcb\057\uffcb\001\002\000\004\066\232\001\002\000\004" +
    "\060\233\001\002\000\004\063\234\001\002\000\046\002" +
    "\uffcd\003\uffcd\040\uffcd\041\uffcd\042\uffcd\043\uffcd\044\uffcd" +
    "\045\uffcd\046\uffcd\047\uffcd\050\uffcd\051\uffcd\052\uffcd\053" +
    "\uffcd\054\uffcd\055\uffcd\056\uffcd\057\uffcd\001\002\000\004" +
    "\062\236\001\002\000\004\060\237\001\002\000\004\063" +
    "\240\001\002\000\046\002\uffd1\003\uffd1\040\uffd1\041\uffd1" +
    "\042\uffd1\043\uffd1\044\uffd1\045\uffd1\046\uffd1\047\uffd1\050" +
    "\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1\055\uffd1\056\uffd1" +
    "\057\uffd1\001\002\000\016\020\024\035\023\062\022\063" +
    "\026\064\025\067\141\001\002\000\004\060\243\001\002" +
    "\000\004\063\244\001\002\000\046\002\uffd9\003\uffd9\040" +
    "\uffd9\041\uffd9\042\uffd9\043\uffd9\044\uffd9\045\uffd9\046\uffd9" +
    "\047\uffd9\050\uffd9\051\uffd9\052\uffd9\053\uffd9\054\uffd9\055" +
    "\uffd9\056\uffd9\057\uffd9\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\012\005\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\050\001\001\000\002\001\001" +
    "\000\006\010\072\011\020\001\001\000\002\001\001\000" +
    "\006\010\026\011\020\001\001\000\006\010\070\011\020" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\066\001\001\000\004\011\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\054\011" +
    "\020\001\001\000\006\010\053\011\020\001\001\000\006" +
    "\010\052\011\020\001\001\000\002\001\001\000\006\010" +
    "\044\011\020\001\001\000\006\010\043\011\020\001\001" +
    "\000\006\010\042\011\020\001\001\000\006\010\041\011" +
    "\020\001\001\000\006\010\040\011\020\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\046\005\007\001\001" +
    "\000\004\005\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\065\001" +
    "\001\000\004\011\064\001\001\000\004\011\063\001\001" +
    "\000\004\011\062\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\074\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\100\011" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\004\103\005\007\001\001\000\004\005\050\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\110\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\006\130\007\131\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\157\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\011\141\012\142\013\143\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\141\013\145\001\001\000\002\001\001\000\006\011" +
    "\141\013\147\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\011\141\012\153\013\143\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\161\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\011\141\012\171\013\143\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\011\141\012\175\013\143\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\011\141\012" +
    "\201\013\143\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\211\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\225\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\011\141\012\241\013\143\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private boolean huboErrores = false;
    private ComplexSymbolFactory.Location lastLocation = new ComplexSymbolFactory.Location(1, 1);

  @Override
  public void syntax_error(Symbol cur_token) {
    huboErrores = true;
    try {
      if (cur_token instanceof ComplexSymbolFactory.ComplexSymbol) {
        ComplexSymbolFactory.ComplexSymbol cs = (ComplexSymbolFactory.ComplexSymbol) cur_token;
        int linea = cs.getLeft().getLine();
        int columna = cs.getLeft().getColumn();
        String tokenName = sym.terminalNames[cur_token.sym];
        String valor = (cur_token.value != null) ? cur_token.value.toString() : "-";

        System.err.println("=== ERROR SINTÁCTICO DETECTADO ===");
        System.err.println("Línea: " + linea + ", Columna: " + columna);
        System.err.println("Token encontrado: " + tokenName + " (valor: " + valor + ")");
        System.err.println("=================================");

        lastLocation = cs.getLeft(); // Guardar para errores no recuperables
      } else {
        System.err.println("Error sintáctico (token no es ComplexSymbol)");
      }
    } catch (Exception e) {
      System.err.println("Error sintáctico (ubicación desconocida): " + e.getMessage());
    }
  }

  @Override
  public void unrecovered_syntax_error(Symbol cur_token) throws Exception {
    huboErrores = true;

    if (cur_token instanceof ComplexSymbolFactory.ComplexSymbol) {
      ComplexSymbolFactory.ComplexSymbol cs = (ComplexSymbolFactory.ComplexSymbol) cur_token;
      int linea = cs.getLeft().getLine();
      int columna = cs.getLeft().getColumn();
      throw new Exception(
              "Error sintáctico no recuperable en línea " + linea +
                      ", columna " + columna
      );
    } else {
      throw new Exception(
              "Error sintáctico no recuperable cerca de línea " +
                      lastLocation.getLine() + ", columna " + lastLocation.getColumn()
      );
    }
  }

    public boolean huboErrores() {
        return huboErrores;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= algoritmo_seccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= algoritmo_seccion SEPARADOR_SECCIONES instrucciones_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // algoritmo_seccion ::= INICIO instrucciones_algoritmo FIN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("algoritmo_seccion",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instrucciones_algoritmo ::= instruccion_algoritmo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones_algoritmo",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instrucciones_algoritmo ::= instrucciones_algoritmo instruccion_algoritmo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones_algoritmo",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instrucciones_algoritmo ::= instrucciones_algoritmo error 
            {
              Object RESULT =null;
		 huboErrores = true; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones_algoritmo",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion_algoritmo ::= VAR IDENTIFICADOR ASIGNACION expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion_algoritmo ::= VAR IDENTIFICADOR ASIGNACION error 
            {
              Object RESULT =null;
		
            huboErrores = true;
            System.err.println("Error: falta expresión después de '='");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion_algoritmo ::= VAR IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion_algoritmo ::= IDENTIFICADOR ASIGNACION expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion_algoritmo ::= IDENTIFICADOR ASIGNACION error 
            {
              Object RESULT =null;
		
            huboErrores = true;
            System.err.println("Error: falta expresión después de '='");
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion_algoritmo ::= SI PAREN_ABRE expresion PAREN_CIERRA ENTONCES instrucciones_algoritmo FINSI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instruccion_algoritmo ::= MIENTRAS PAREN_ABRE expresion PAREN_CIERRA HACER instrucciones_algoritmo FINMIENTRAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccion_algoritmo ::= MOSTRAR STRING 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // instruccion_algoritmo ::= MOSTRAR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // instruccion_algoritmo ::= LEER IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_algoritmo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion ::= expresion AND expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion ::= NOT expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion_numerica ::= expresion_numerica MAS expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion_numerica ::= expresion_numerica MENOS expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion_numerica ::= expresion_numerica POR expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion_numerica ::= expresion_numerica DIV expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion_numerica ::= MENOS expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion_numerica ::= PAREN_ABRE expresion_numerica PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion_numerica ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion_numerica ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion_numerica ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // instrucciones_config ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones_config",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // instrucciones_config ::= instrucciones_config instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones_config",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // instrucciones_config ::= instrucciones_config error 
            {
              Object RESULT =null;
		 huboErrores = true; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones_config",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // instruccion_config ::= CONF_DEFAULT ASIGNACION ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instruccion_config ::= CONF_COLOR_TEXTO_SI ASIGNACION color PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion_config ::= CONF_COLOR_SI ASIGNACION color PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion_config ::= CONF_FIGURA_SI ASIGNACION FIGURA PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instruccion_config ::= CONF_LETRA_SI ASIGNACION IDENTIFICADOR PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= CONF_LETRA_SIZE_SI ASIGNACION expresion_numerica PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= CONF_COLOR_TEXTO_MIENTRAS ASIGNACION color PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= CONF_COLOR_MIENTRAS ASIGNACION color PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // instruccion_config ::= CONF_FIGURA_MIENTRAS ASIGNACION FIGURA PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_config ::= CONF_LETRA_MIENTRAS ASIGNACION IDENTIFICADOR PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_config ::= CONF_LETRA_SIZE_MIENTRAS ASIGNACION expresion_numerica PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // instruccion_config ::= CONF_COLOR_TEXTO_BLOQUE ASIGNACION color PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // instruccion_config ::= CONF_COLOR_BLOQUE ASIGNACION color PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // instruccion_config ::= CONF_FIGURA_BLOQUE ASIGNACION FIGURA PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // instruccion_config ::= CONF_LETRA_BLOQUE ASIGNACION IDENTIFICADOR PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // instruccion_config ::= CONF_LETRA_SIZE_BLOQUE ASIGNACION expresion_numerica PIPE ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // color ::= componente_color COMA componente_color COMA componente_color 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // color ::= COLOR_HEX 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // componente_color ::= expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("componente_color",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
