
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONF_COLOR_TEXTO_SI = 31;
  public static final int POR = 15;
  public static final int ENTERO = 49;
  public static final int SI = 5;
  public static final int MOSTRAR = 11;
  public static final int DIFERENTE = 19;
  public static final int ENTONCES = 6;
  public static final int PAREN_CIERRA = 28;
  public static final int FIN = 3;
  public static final int IDENTIFICADOR = 48;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int CONF_LETRA_MIENTRAS = 39;
  public static final int IGUAL = 18;
  public static final int FINMIENTRAS = 10;
  public static final int OR = 25;
  public static final int MIENTRAS = 8;
  public static final int DIV = 16;
  public static final int CONF_COLOR_SI = 32;
  public static final int CONF_LETRA_SI = 34;
  public static final int COLOR_HEX = 53;
  public static final int DECIMAL = 50;
  public static final int EOF = 0;
  public static final int SEPARADOR_SECCIONES = 29;
  public static final int CONF_LETRA_SIZE_BLOQUE = 45;
  public static final int CONF_FIGURA_MIENTRAS = 38;
  public static final int CONF_FIGURA_SI = 33;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int PIPE = 46;
  public static final int MENOS = 14;
  public static final int MENOR = 21;
  public static final int CONF_COLOR_BLOQUE = 42;
  public static final int ASIGNACION = 17;
  public static final int MAYOR = 20;
  public static final int CONF_LETRA_SIZE_SI = 35;
  public static final int CONF_COLOR_TEXTO_BLOQUE = 41;
  public static final int CONF_COLOR_MIENTRAS = 37;
  public static final int CONF_LETRA_BLOQUE = 44;
  public static final int PAREN_ABRE = 27;
  public static final int MAYOR_IGUAL = 22;
  public static final int LEER = 12;
  public static final int CONF_FIGURA_BLOQUE = 43;
  public static final int CONF_DEFAULT = 30;
  public static final int HACER = 9;
  public static final int CONF_COLOR_TEXTO_MIENTRAS = 36;
  public static final int STRING = 51;
  public static final int INICIO = 2;
  public static final int MENOR_IGUAL = 23;
  public static final int CONF_LETRA_SIZE_MIENTRAS = 40;
  public static final int FINSI = 7;
  public static final int VAR = 4;
  public static final int FIGURA = 52;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "FINSI",
  "MIENTRAS",
  "HACER",
  "FINMIENTRAS",
  "MOSTRAR",
  "LEER",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIGNACION",
  "IGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "PAREN_ABRE",
  "PAREN_CIERRA",
  "SEPARADOR_SECCIONES",
  "CONF_DEFAULT",
  "CONF_COLOR_TEXTO_SI",
  "CONF_COLOR_SI",
  "CONF_FIGURA_SI",
  "CONF_LETRA_SI",
  "CONF_LETRA_SIZE_SI",
  "CONF_COLOR_TEXTO_MIENTRAS",
  "CONF_COLOR_MIENTRAS",
  "CONF_FIGURA_MIENTRAS",
  "CONF_LETRA_MIENTRAS",
  "CONF_LETRA_SIZE_MIENTRAS",
  "CONF_COLOR_TEXTO_BLOQUE",
  "CONF_COLOR_BLOQUE",
  "CONF_FIGURA_BLOQUE",
  "CONF_LETRA_BLOQUE",
  "CONF_LETRA_SIZE_BLOQUE",
  "PIPE",
  "COMA",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "STRING",
  "FIGURA",
  "COLOR_HEX"
  };
}

