package com.example.compiladorespractica1.utils

import lexer.sym

object TokenHelper {
    fun getTokenName(tokenId: Int): String {
        return when (tokenId) {
            sym.INICIO -> "INICIO"
            sym.FIN -> "FIN"
            sym.VAR -> "VAR"
            sym.SI -> "SI"
            sym.ENTONCES -> "ENTONCES"
            sym.FINSI -> "FINSI"
            sym.MIENTRAS -> "MIENTRAS"
            sym.HACER -> "HACER"
            sym.FINMIENTRAS -> "FINMIENTRAS"
            sym.MOSTRAR -> "MOSTRAR"
            sym.LEER -> "LEER"
            sym.MAS -> "MAS"
            sym.MENOS -> "MENOS"
            sym.POR -> "POR"
            sym.DIV -> "DIV"
            sym.ASIGNACION -> "ASIGNACION"
            sym.IGUAL -> "IGUAL"
            sym.DIFERENTE -> "DIFERENTE"
            sym.MAYOR -> "MAYOR"
            sym.MENOR -> "MENOR"
            sym.MAYOR_IGUAL -> "MAYOR_IGUAL"
            sym.MENOR_IGUAL -> "MENOR_IGUAL"
            sym.AND -> "AND"
            sym.OR -> "OR"
            sym.NOT -> "NOT"
            sym.PAREN_ABRE -> "PAREN_ABRE"
            sym.PAREN_CIERRA -> "PAREN_CIERRA"
            sym.ENTERO -> "ENTERO"
            sym.DECIMAL -> "DECIMAL"
            sym.IDENTIFICADOR -> "IDENTIFICADOR"
            sym.STRING -> "STRING"
            sym.SEPARADOR_SECCIONES -> "SEP_SECCIONES"
            sym.CONF_DEFAULT -> "CONF_DEFAULT"
            sym.CONF_COLOR_TEXTO_SI -> "COLOR_TEXTO_SI"
            sym.CONF_COLOR_SI -> "COLOR_SI"
            sym.CONF_FIGURA_SI -> "FIGURA_SI"
            sym.CONF_LETRA_SI -> "LETRA_SI"
            sym.CONF_LETRA_SIZE_SI -> "LETRA_SIZE_SI"
            sym.CONF_COLOR_TEXTO_MIENTRAS -> "COLOR_TEXTO_MIENTRAS"
            sym.CONF_COLOR_MIENTRAS -> "COLOR_MIENTRAS"
            sym.CONF_FIGURA_MIENTRAS -> "FIGURA_MIENTRAS"
            sym.CONF_LETRA_MIENTRAS -> "LETRA_MIENTRAS"
            sym.CONF_LETRA_SIZE_MIENTRAS -> "LETRA_SIZE_MIENTRAS"
            sym.CONF_COLOR_TEXTO_BLOQUE -> "COLOR_TEXTO_BLOQUE"
            sym.CONF_COLOR_BLOQUE -> "COLOR_BLOQUE"
            sym.CONF_FIGURA_BLOQUE -> "FIGURA_BLOQUE"
            sym.CONF_LETRA_BLOQUE -> "LETRA_BLOQUE"
            sym.CONF_LETRA_SIZE_BLOQUE -> "LETRA_SIZE_BLOQUE"
            sym.PIPE -> "PIPE"
            sym.COMA -> "COMA"
            sym.FIGURA -> "FIGURA"
            sym.COLOR_HEX -> "COLOR_HEX"
            sym.EOF -> "EOF"
            else -> "DESCONOCIDO($tokenId)"
        }
    }
}